const state = AppStore.create({
  auth: {
    status: 'checking',
    mode: 'login',
    profile: null,
    error: '',
  },
  projects: [],
  agents: [],
  groups: [],
  friends: [],
  friendRequests: [],
  currentProjectId: null,
  agentCurrentId: null,
  groupCurrentId: null,
  friendCurrentId: null,
  sessions: [],
  currentId: null,
  streaming: null,
  pendingAttachments: [],
  model: 'MiniMax-M3',
  backendModel: null,
  backendOk: false,
  theme: localStorage.getItem('mc-theme') || 'light',
});
