import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const read = (path) => readFile(new URL(`../${path}`, import.meta.url), 'utf8')

test('dependencies are pinned and quality scripts exist', async () => {
  const pkg = JSON.parse(await read('package.json'))
  const versions = [...Object.values(pkg.dependencies), ...Object.values(pkg.devDependencies)]
  assert.ok(versions.every((version) => !String(version).includes('latest')))
  assert.equal(pkg.scripts.test, 'node --test tests/site-contracts.test.mjs')
  assert.equal(pkg.scripts['dev:shared'], 'node scripts/shared-preview.mjs')
  assert.match(pkg.scripts.dev, /strictPort/)
  assert.match(pkg.scripts.preview, /strictPort/)
  assert.ok(pkg.scripts.typecheck)
  assert.ok(pkg.scripts.build)
  assert.equal(pkg.scripts.check, 'pnpm test && pnpm run typecheck && pnpm run build')
})

test('shared preview has explicit ownership and identity', async () => {
  const previewScript = await read('scripts/shared-preview.mjs')
  const viteConfig = await read('vite.config.ts')
  const instructions = await read('AGENTS.md')

  assert.match(previewScript, /git.*worktree.*list/s)
  assert.match(previewScript, /--strictPort/)
  assert.match(viteConfig, /catsco-preview-identity/)
  assert.match(viteConfig, /\/__catsco_preview/)
  assert.match(instructions, /Port `5175` is reserved for the shared integration preview/)
})

test('public routes have unique metadata and page contracts', async () => {
  const routes = await read('src/site-routes.ts')
  const entries = [...routes.matchAll(/page: '([^']+)',\s+path: '([^']+)',\s+title: '([^']+)',\s+description: '([^']+)'/g)]
  const expectedPaths = ['/', '/pricing', '/login', '/download', '/contact', '/privacy', '/terms']

  assert.equal(entries.length, expectedPaths.length)
  assert.deepEqual(entries.map(([, , path]) => path), expectedPaths)
  assert.equal(new Set(entries.map(([, , path]) => path)).size, entries.length)
  for (const [, , , title, description] of entries) {
    assert.match(title, /CatsCo/)
    assert.ok(description.length >= 20)
  }

  assert.ok(routes.includes("pathname.replace(/\\/{2,}/g, '/')"))
  assert.match(routes, /'页面未找到 — CatsCo'/)
  assert.match(routes, /robots\.content = 'noindex, follow'/)
  assert.match(routes, /CatsCo Free、Pro、Max 与 Business Start/)
  assert.doesNotMatch(routes, /path: '\/enterprise'/)
  const app = await read('src/App.tsx')
  const main = await read('src/main.tsx')
  assert.doesNotMatch(app, /EnterprisePage/)
  assert.doesNotMatch(main, /pages\/enterprise\.css/)
})

test('home and pricing conversion copy follows current page briefs', async () => {
  const hero = await read('src/components/Hero.tsx')
  const footer = await read('src/components/Footer.tsx')
  const header = await read('src/components/Header.tsx')
  const siteLinks = await read('src/site-links.ts')
  const taskDemo = await read('src/components/TaskDemoSection.tsx')
  const team = await read('src/components/Team.tsx')
  const workflow = await read('src/components/WorkflowSection.tsx')
  const pricing = await read('src/components/PricingPage.tsx')
  const login = await read('src/components/LoginPage.tsx')
  const homeCss = await read('src/styles/pages/home.css')
  const pricingCss = await read('src/styles/pages/pricing.css')

  assert.match(hero, />CatsCo<\/span>/)
  assert.match(hero, />你的专业AI员工<\/span>/)
  assert.doesNotMatch(hero, /hero-title-comma/)
  assert.match(hero, />\s*立刻开始\s*</)
  assert.match(footer, />\s*立刻开始\s*</)
  assert.match(taskDemo, />REAL WORKBENCH</)
  assert.match(team, />ABOUT CATSCO</)
  for (const iconName of ['goalPath', 'deviceHandoff', 'reusableMemory']) {
    assert.match(workflow, new RegExp(`icon: '${iconName}'`))
  }
  assert.doesNotMatch(workflow, /workflow-icon-\$\{card\.tone\}/)
  assert.match(homeCss, /\.workflow-icon \{[^}]*color: #858a88;[^}]*background: transparent;[^}]*box-shadow: none;/s)
  assert.match(workflow, /strokeWidth="1\.4"/)
  assert.match(homeCss, /\.workflow-icon svg \{[^}]*width: 30px;[^}]*height: 30px;/s)
  assert.match(homeCss, /\.workflow-card:hover \.workflow-icon \{[^}]*color: #f2f4f3;/s)
  assert.doesNotMatch(homeCss, /\.workflow-card:hover \.workflow-icon \{[^}]*background:/s)
  assert.match(homeCss, /@keyframes workflow-goal-arrow/)
  assert.match(workflow, /className="workflow-icon-cycle"/)
  assert.equal((workflow.match(/workflow-icon-cycle-arrow/g) || []).length, 6)
  assert.match(homeCss, /\.workflow-card:hover \.workflow-icon-cycle \{[^}]*rotate\(120deg\);/s)
  assert.equal((workflow.match(/workflow-icon-memory-line workflow-icon-memory-line-/g) || []).length, 4)
  assert.doesNotMatch(workflow, /workflow-icon-memory-return/)
  assert.match(homeCss, /@keyframes workflow-memory-line-draw/)
  assert.match(homeCss, /\.workflow-card:hover \.workflow-icon-memory-line-four \{[^}]*animation-delay: 165ms;/s)
  assert.match(homeCss, /\.workflow-card > p \{[^}]*font-size: 0\.95rem;[^}]*line-height: 1\.62;[^}]*text-wrap: pretty;/s)
  assert.match(homeCss, /@media \(min-width: 1200px\) \{\s*\.workflow-card \{\s*padding-inline: 30px;/s)
  assert.match(homeCss, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.workflow-icon \*/)
  assert.match(footer, />CATSCO · FROM GOAL TO OUTCOME</)
  assert.match(footer, />拥抱你的第一位 AI 员工</)
  assert.match(footer, /从下一项任务开始，让 CatsCo 帮你持续推进并交付成果。/)
  assert.doesNotMatch(footer, /准备好拥有你的第一个AI员工了吗？/)
  assert.doesNotMatch(footer, /从一个目标开始，让 CatsCo 持续推进，并将完成的成果带回给你。/)
  for (const label of ['PERSONAL PLANS', 'BUSINESS SERVICE', 'CORE SERVICE SCOPE', 'EARLY ACCESS', 'PLAN COMPARISON']) {
    assert.match(pricing, new RegExp(`>${label}<`))
  }
  assert.doesNotMatch(footer, /企业版/)
  assert.match(footer, /href: GITHUB_URL/)
  assert.match(header, /href=\{GITHUB_URL\}/)
  assert.match(siteLinks, /GITHUB_URL = 'https:\/\/github\.com\/buildsense-ai'/)
  assert.match(pricing, /queryPlan: 'free'/)
  assert.match(pricing, /queryPlan: 'personal'/)
  assert.match(pricing, /queryPlan: 'pro'/)
  assert.match(pricing, /service=business-start|service: 'business-start'/)
  assert.match(login, /appLoginUrl/)
  assert.match(login, /公开官网不会接收或保存密码/)
  assert.match(siteLinks, /APP_BASE_URL/)
  assert.match(siteLinks, /appRegisterUrl/)

  for (const action of ['header-social-link', 'header-login', 'header-download']) {
    for (const state of ['', ':hover', ':active']) {
      const homeState = homeCss.match(new RegExp(`body:has\\(main > \\.hero-section\\) \\.site-header \\.${action}${state} \\{([^}]+)\\}`))
      const pricingState = pricingCss.match(new RegExp(`\\.min-h-screen:has\\(\\.pricing-page\\) > \\.site-header \\.${action}${state} \\{([^}]+)\\}`))
      assert.ok(homeState && pricingState)
      assert.equal(homeState[1].trim(), pricingState[1].trim())
    }
  }
  assert.equal((homeCss.match(/background: #2b2b2b;/g) || []).length, 3)
  assert.equal((pricingCss.match(/background: #2b2b2b;/g) || []).length, 3)
})

test('SPA hosting fallbacks cover deep links', async () => {
  const vercel = JSON.parse(await read('vercel.json'))
  const redirects = (await read('public/_redirects')).trim()

  assert.deepEqual(vercel.rewrites, [{ source: '/(.*)', destination: '/index.html' }])
  assert.equal(redirects, '/* /index.html 200')
})

test('document shell provides language, viewport, and initial metadata', async () => {
  const html = await read('index.html')
  assert.match(html, /<html lang="zh-CN">/)
  assert.match(html, /name="viewport" content="width=device-width, initial-scale=1\.0"/)
  assert.match(html, /name="description"/)
  assert.match(html, /<title>[^<]*CatsCo[^<]*<\/title>/)
})

test('contact page follows the current dark form and validation contract', async () => {
  const contact = await read('src/components/ContactPage.tsx')
  const contactStyles = await read('src/styles/pages/contact.css')
  const main = await read('src/main.tsx')

  assert.match(contact, /requestedTopic === 'enterprise' \|\| requestedTopic === 'download'/)
  assert.match(contact, /BUSINESS INQUIRY/)
  assert.match(contact, /DOWNLOAD & RELEASE UPDATES/)
  assert.match(contact, /PRODUCT INQUIRY/)
  assert.match(contact, /firstInvalidControl\?\.focus\(\{ preventScroll: true \}\)/)
  assert.match(contact, /firstInvalidControl\?\.scrollIntoView\(\{ block: 'center', behavior: 'instant' \}\)/)
  assert.match(contact, /<form ref=\{formRef\} className="contact-form-grid"/)
  assert.match(contact, /onPointerDownCapture=\{handleFieldPointerDown\}/)
  assert.match(contact, /团队名称与规模/)
  assert.match(contact, /内容仍保留在你的浏览器中，没有被发送/)
  assert.match(contact, /className="contact-form-grid"/)
  assert.match(contact, /autoComplete="name"/)
  assert.match(contact, /autoComplete="email"/)
  assert.match(contact, /autoComplete="organization"/)
  assert.match(contact, /type="hidden" name="teamSize" value=\{teamSize\}/)
  assert.match(contact, /aria-haspopup="listbox"/)
  assert.match(contact, /role="option"/)
  assert.doesNotMatch(contact, /<select id="contact-size"/)
  assert.match(contactStyles, /\.contact-page \{[^}]*background: #171717;/s)
  assert.match(contactStyles, /\.contact-page \.contact-team-size-menu \{/)
  assert.match(contactStyles, /\.contact-page \.form-field input,[\s\S]*?\.contact-page \.form-field textarea \{[^}]*min-height: 52px;/)
  assert.match(contactStyles, /\.contact-page \.contact-submit \{[^}]*font-size: 17px;/s)
  assert.match(contactStyles, /@media \(max-width: 640px\)/)
  assert.match(contactStyles, /@media \(prefers-reduced-motion: reduce\)/)
  assert.match(contact, /import '\.\.\/styles\/pages\/contact\.css'/)
  assert.match(contact, /import '\.\.\/styles\/pages\/content\.css'/)
})

test('shared design rules use CatsCo brand direction', async () => {
  const master = await read('design-system/catsco/MASTER.md')
  const base = await read('src/styles/base.css')
  assert.match(master, /#1A9D7A/i)
  assert.doesNotMatch(master, /Modern Dark|#7C3AED/i)
  assert.match(master, /Chinese display headings use a calm medium weight with slightly open tracking/)
  assert.match(base, /--cats-heading-display-weight: 500;/)
  assert.match(base, /--cats-heading-display-tracking: 0\.012em;/)
  assert.match(base, /--cats-heading-section-weight: 500;/)
  assert.match(base, /--cats-heading-section-tracking: 0\.008em;/)
  assert.match(base, /--cats-heading-card-weight: 600;/)
  assert.match(base, /--cats-heading-latin-tracking: -0\.025em;/)
})

test('source avoids known interaction regressions', async () => {
  const files = ['src/App.tsx', 'src/components/Header.tsx', 'src/components/Footer.tsx', 'src/styles/base.css', 'src/styles/site-header.css', 'src/styles/site-footer.css', 'src/styles/pages/contact.css', 'src/styles/legacy-responsive.css']
  const source = (await Promise.all(files.map(read))).join('\n')
  assert.doesNotMatch(source, /transition:\s*all/i)
  assert.doesNotMatch(source, /user-scalable\s*=\s*no|maximum-scale\s*=\s*1/i)

  const app = await read('src/App.tsx')
  const header = await read('src/components/Header.tsx')
  const headerStyles = await read('src/styles/site-header.css')
  const footerStyles = await read('src/styles/site-footer.css')
  const pricingStyles = await read('src/styles/pages/pricing.css')
  const responsive = await read('src/styles/legacy-responsive.css')
  assert.match(app, /className="skip-link" href="#main-content"/)
  assert.match(app, /route \? renderPage\(route\.page\) : <AsyncNotFoundPage \/>/)
  assert.match(header, /aria-expanded=\{menuOpen\}/)
  assert.match(header, /inert=\{!menuOpen\}/)
  assert.match(header, /event\.key !== 'Escape'/)
  assert.match(header, /label: '首页', href: homeHref\('#top'\), active: isHomeTop/)
  assert.doesNotMatch(header, /label: '企业', href: '\/enterprise'/)
  assert.match(header, /className="site-primary-nav/)
  assert.doesNotMatch(header, /header-social-label/)
  assert.match(header, /className="site-header-brand-mark" src="\/catsco-brand-mark\.webp" alt="" width="256" height="96"/)
  assert.match(header, /className="site-header-wordmark" src="\/catsco-wordmark.webp" alt="" width="512" height="93"/)
  assert.match(header, /aria-label="CatsCo 首页"/)
  assert.doesNotMatch(header, /<BrandMark/)
  assert.doesNotMatch(header, />CatsCo<\/span>/)
  assert.match(headerStyles, /\.site-header-brand-mark \{[^}]*width: 48px;[^}]*height: 24px;/s)
  assert.match(headerStyles, /\.site-header-wordmark \{[^}]*width: 84px;[^}]*height: auto;/s)
  assert.match(headerStyles, /@media \(max-width: 767px\)[\s\S]*\.site-header-brand-mark \{[^}]*width: 41px;[^}]*height: 21px;/s)
  assert.match(headerStyles, /@media \(max-width: 767px\)[\s\S]*\.site-header-wordmark \{[^}]*width: 72px;/s)
  assert.match(headerStyles, /\.site-header-brand-mark,[^{]+\.site-header-wordmark \{[^}]*object-fit: contain;/s)
  assert.match(headerStyles, /\.header-social-link \{[^}]*border: 0;/s)
  assert.match(headerStyles, /\.header-login \{[^}]*border: 0;/s)
  assert.match(headerStyles, /\.header-download \{[^}]*border: 0;/s)
  assert.match(headerStyles, /\.header-actions \{[^}]*gap: 8px;/s)
  assert.match(footerStyles, /\.final-footer-primary,[^{]+\.final-footer-secondary \{[^}]*background: rgba\(255, 255, 255, 0\.08\);/s)
  assert.match(footerStyles, /\.final-footer-primary,[^{]+\.final-footer-secondary \{[^}]*font-size: 16px;/s)
  assert.match(footerStyles, /\.final-footer-primary:hover,[^{]+\.final-footer-secondary:hover \{[^}]*background: #f4fbf8;/s)
  assert.match(footerStyles, /\.final-footer-primary:active,[^{]+\.final-footer-secondary:active \{[^}]*background: #dff3ec;/s)
  assert.match(footerStyles, /--final-footer-muted: rgba\(255, 255, 255, 0\.5\);/)
  assert.match(footerStyles, /\.final-footer-brand > span \{[^}]*color: var\(--final-footer-muted\);/s)
  assert.match(footerStyles, /\.final-footer-copyright \{[^}]*color: var\(--final-footer-muted\);/s)
  assert.match(pricingStyles, /\.pricing-card \{[^}]*border: 1px solid transparent;/s)
  assert.doesNotMatch(pricingStyles, /\.pricing-card\.is-(?:free|personal|pro) \{[^}]*border-color:/s)
  assert.match(pricingStyles, /\.pricing-card\.is-free:hover \{[^}]*border-color: #616161;/s)
  assert.match(pricingStyles, /\.pricing-card\.is-pro:hover \{[^}]*border-color: var\(--pricing-accent\);/s)
  assert.match(pricingStyles, /\.pricing-business \{[^}]*border: 1px solid transparent;/s)
  assert.match(pricingStyles, /\.pricing-business:hover,[^{]+\.pricing-business:focus-within \{[^}]*border-color: var\(--pricing-accent\);/s)
  assert.match(pricingStyles, /\.pricing-access \{[^}]*border: 1px solid transparent;/s)
  assert.match(pricingStyles, /\.pricing-access:hover,[^{]+\.pricing-access:focus-within \{[^}]*border-color: #616161;/s)
  assert.match(responsive, /@media \(prefers-reduced-motion: reduce\)/)
})
