FROM golang:1.26.5-alpine3.24 AS builder
ARG GOPROXY=https://proxy.golang.org,direct
ENV GOPROXY=${GOPROXY}
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -mod=readonly -o openchat-server ./server/cmd/

FROM alpine:3.24.1
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/openchat-server .
COPY --from=builder /app/server/tinode.conf .
EXPOSE 6061 6062
CMD ["./openchat-server", "tinode.conf"]
