#!/usr/bin/env bash
set -Eeuo pipefail

[[ "${CATSCO_ARTIFACT_GATEWAY_ENABLED:-0}" == "1" ]] \
  || { echo '{"ok":true,"status":"disabled"}'; exit 0; }

OPS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
JUMP_IP="${CTYUN_JUMP_IP:-}"
JUMP_PORT="${CTYUN_JUMP_PORT:-22}"
JUMP_USER="${CTYUN_JUMP_USER:-root}"
JUMP_KEY="${CTYUN_JUMP_KEY:-/var/lib/catsco-worker/jump_host_ed25519}"
STATE_ROOT="${CTYUN_WORKER_STATE_ROOT:-/var/lib/catsco-worker}"
HOST_SUFFIX="${CATSCO_ARTIFACT_HOST_SUFFIX:-artifacts.catsco.fun}"
PUBLIC_IP="${CATSCO_ARTIFACT_GATEWAY_PUBLIC_IP:-$JUMP_IP}"
HTTPS_PORT="${CATSCO_ARTIFACT_GATEWAY_HTTPS_PORT:-19991}"
CERT_NAME="catsco-artifact-gateway"
CERT_ROOT="/etc/letsencrypt/live/$CERT_NAME"
REMOTE_ROOT="/usr/local/lib/catsco-artifact-gateway"
REMOTE_ENV="/etc/catsco-artifact-gateway/dns.env"

for file in artifact-gateway-route.mjs volcengine-dns.mjs dns01-certbot-hook.mjs; do
  [[ -f "$OPS_DIR/$file" ]] || { echo "error: missing gateway asset: $file" >&2; exit 2; }
done
[[ -n "$JUMP_IP" && -f "$JUMP_KEY" ]] \
  || { echo "error: jump host endpoint or key is unavailable" >&2; exit 2; }
[[ -n "${CATSCO_ARTIFACT_DNS_ACCESS_KEY:-}" && -n "${CATSCO_ARTIFACT_DNS_SECRET_KEY:-}" ]] \
  || { echo "error: Artifact DNS credentials are unavailable" >&2; exit 2; }

"$OPS_DIR/ensure-artifact-gateway-network.sh" >/dev/null

mkdir -p "$STATE_ROOT"
chmod 600 "$JUMP_KEY"
ssh_opts=(-i "$JUMP_KEY" -p "$JUMP_PORT" -o BatchMode=yes -o ConnectTimeout=10
  -o ServerAliveInterval=15 -o ServerAliveCountMax=3
  -o StrictHostKeyChecking=accept-new
  -o UserKnownHostsFile="$STATE_ROOT/artifact_gateway_known_hosts")
ssh_run() { timeout -s TERM -k 30 1200s ssh "${ssh_opts[@]}" "$JUMP_USER@$JUMP_IP" "$@"; }

ssh_run "export DEBIAN_FRONTEND=noninteractive; apt-get update -qq && apt-get install -y -qq nginx certbot nodejs curl jq openssl util-linux >/dev/null"
ssh_run "systemctl enable --now certbot.timer >/dev/null && systemctl is-enabled --quiet certbot.timer && systemctl is-active --quiet certbot.timer"
ssh_run "install -d -m 0755 '$REMOTE_ROOT' /etc/catsco-artifact-gateway /var/lib/catsco-artifact-gateway /var/lib/catsco-artifact-gateway/dns01-state"

for file in artifact-gateway-route.mjs volcengine-dns.mjs dns01-certbot-hook.mjs; do
  ssh_run "cat > '$REMOTE_ROOT/$file' && chmod 0755 '$REMOTE_ROOT/$file'" < "$OPS_DIR/$file"
done

shell_quote() { printf "'%s'" "${1//\'/\'\\\'\'}"; }
DNS_ENV="$(printf '%s\n' \
  "VOLC_ACCESSKEY=$(shell_quote "$CATSCO_ARTIFACT_DNS_ACCESS_KEY")" \
  "VOLC_SECRETKEY=$(shell_quote "$CATSCO_ARTIFACT_DNS_SECRET_KEY")" \
  "CATSCO_ARTIFACT_DNS_ZONE=$(shell_quote "${CATSCO_ARTIFACT_DNS_ZONE:-catsco.fun}")" \
  "CATSCO_ARTIFACT_HOST_SUFFIX=$(shell_quote "$HOST_SUFFIX")" \
  "CATSCO_ARTIFACT_DNS_STATE_DIR=$(shell_quote /var/lib/catsco-artifact-gateway/dns01-state)")"
ssh_run "cat > '$REMOTE_ENV' && chmod 0600 '$REMOTE_ENV'" <<<"$DNS_ENV"

AUTH_HOOK='#!/bin/sh
set -eu
set -a
. /etc/catsco-artifact-gateway/dns.env
set +a
exec /usr/bin/node /usr/local/lib/catsco-artifact-gateway/dns01-certbot-hook.mjs auth'
CLEANUP_HOOK='#!/bin/sh
set -eu
set -a
. /etc/catsco-artifact-gateway/dns.env
set +a
exec /usr/bin/node /usr/local/lib/catsco-artifact-gateway/dns01-certbot-hook.mjs cleanup'
DEPLOY_HOOK='#!/bin/sh
set -eu
nginx -t
systemctl reload nginx'
ROUTE_WRAPPER='#!/bin/sh
set -eu
exec flock -w 30 /run/catsco-artifact-route.lock /usr/bin/node /usr/local/lib/catsco-artifact-gateway/artifact-gateway-route.mjs "$@"'
ssh_run "cat > /usr/local/sbin/catsco-artifact-dns-auth && chmod 0755 /usr/local/sbin/catsco-artifact-dns-auth" <<<"$AUTH_HOOK"
ssh_run "cat > /usr/local/sbin/catsco-artifact-dns-cleanup && chmod 0755 /usr/local/sbin/catsco-artifact-dns-cleanup" <<<"$CLEANUP_HOOK"
ssh_run "cat > /usr/local/sbin/catsco-artifact-cert-deploy && chmod 0755 /usr/local/sbin/catsco-artifact-cert-deploy" <<<"$DEPLOY_HOOK"
ssh_run "cat > /usr/local/sbin/catsco-artifact-route && chmod 0755 /usr/local/sbin/catsco-artifact-route" <<<"$ROUTE_WRAPPER"

EMPTY_ROUTES='# Generated by catsco-artifact-route. Do not edit.
map $host $catsco_artifact_backend {
    default 127.0.0.1:1;
}

map $host $catsco_artifact_route_found {
    default 0;
}'
ssh_run "test -f /etc/nginx/conf.d/00-catsco-artifact-routes.conf || cat > /etc/nginx/conf.d/00-catsco-artifact-routes.conf" <<<"$EMPTY_ROUTES"

wildcard="*.$HOST_SUFFIX"
certificate_ready=0
if ssh_run "test -s '$CERT_ROOT/fullchain.pem' -a -s '$CERT_ROOT/privkey.pem' && openssl x509 -checkend 2592000 -noout -in '$CERT_ROOT/fullchain.pem' && openssl x509 -in '$CERT_ROOT/fullchain.pem' -noout -ext subjectAltName | grep -Fq '$wildcard'" >/dev/null 2>&1; then
  certificate_ready=1
fi
if [[ "$certificate_ready" == "0" ]]; then
  ssh_run "certbot certonly --manual --preferred-challenges dns --manual-auth-hook /usr/local/sbin/catsco-artifact-dns-auth --manual-cleanup-hook /usr/local/sbin/catsco-artifact-dns-cleanup --deploy-hook /usr/local/sbin/catsco-artifact-cert-deploy --non-interactive --agree-tos --register-unsafely-without-email --cert-name '$CERT_NAME' -d '$wildcard'"
fi

NGINX_CONFIG="$(cat <<EOF
server {
    listen $HTTPS_PORT ssl;
    listen [::]:$HTTPS_PORT ssl;
    server_name *.$HOST_SUFFIX;

    ssl_certificate $CERT_ROOT/fullchain.pem;
    ssl_certificate_key $CERT_ROOT/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location = /__artifact_gateway_health {
        default_type application/json;
        add_header Cache-Control "no-store" always;
        return 200 '{"ok":true,"contract_version":"catsco.artifact-gateway.v1"}';
    }

    location /artifacts/ {
        if (\$catsco_artifact_route_found = 0) { return 404; }
        proxy_pass http://\$catsco_artifact_backend;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_connect_timeout 5s;
        proxy_read_timeout 60s;
    }

    location / { return 404; }
}
EOF
)"
ssh_run "cat > /etc/nginx/conf.d/10-catsco-artifact-gateway.conf && nginx -t && systemctl enable --now nginx && systemctl reload nginx" <<<"$NGINX_CONFIG"

probe_host="gateway-probe.$HOST_SUFFIX"
curl --fail --silent --show-error --max-time 15 \
  --resolve "$probe_host:$HTTPS_PORT:$PUBLIC_IP" \
  "https://$probe_host:$HTTPS_PORT/__artifact_gateway_health" >/dev/null

printf '{"ok":true,"status":"ready","public_ip":"%s","port":%s,"host_suffix":"%s"}\n' \
  "$PUBLIC_IP" "$HTTPS_PORT" "$HOST_SUFFIX"
