server {
    listen 443 ssl http2;
    server_name catsco.cc www.catsco.cc;

    ssl_certificate /etc/letsencrypt/live/catsco.cc/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/catsco.cc/privkey.pem;

    return 301 https://preview.catsco.cc$request_uri;
}
